<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ext"
    nsURI="http:///org.eclipse.emf.test.models/ext" nsPrefix="org.eclipse.emf.test.models.ext">
  <eClassifiers xsi:type="ecore:EClass" name="ExtE" eSuperTypes="ref.ecore#//E">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="f" upperBound="-1" eType="#//F"
        containment="true" eOpposite="#//F/e"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="F">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="e" lowerBound="1" eType="#//ExtE"
        transient="true" eOpposite="#//ExtE/f"/>
  </eClassifiers>
</ecore:EPackage>
