<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="xrefsopposite" nsURI="http://www.eclipse.org/EMF/2019/test/xrefsopposite"
    nsPrefix="xrefso">
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//AbstractA">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref1" upperBound="-1" eType="#//A"
        eOpposite="#//A/oref1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oref1" upperBound="-1"
        eType="#//A" eOpposite="#//A/ref1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref2" upperBound="-1" eType="#//A"
        eOpposite="#//A/oref2"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="oref2" upperBound="-1"
        eType="#//A" eOpposite="#//A/ref2"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref3" upperBound="-1" eType="#//A"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningAPkg" eType="#//APkg"
        eOpposite="#//APkg/ownedAs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="APkg" eSuperTypes="#//AbstractA">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAs" upperBound="-1"
        eType="#//A" containment="true" eOpposite="#//A/owningAPkg"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractA" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
