/*
 * generated by Xtext
 */
package org.eclipse.emf.ecore.xcore.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.eclipse.emf.ecore.xcore.ui.internal.XcoreActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XcoreExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XcoreActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XcoreActivator.getInstance().getInjector(XcoreActivator.ORG_ECLIPSE_EMF_ECORE_XCORE_XCORE);
	}
	
}
