/*
 * generated by Xtext
 */
package org.eclipse.emf.ecore.xcore.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.emf.ecore.xcore.ui.internal.XcoreActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XcoreExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(XcoreActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		XcoreActivator activator = XcoreActivator.getInstance();
		return activator != null ? activator.getInjector(XcoreActivator.ORG_ECLIPSE_EMF_ECORE_XCORE_XCORE) : null;
	}

}
